language: android
jdk: oraclejdk8
before_install:
  - yes | sdkmanager "platforms;android-28"

env:
  global:
    - ANDROID_API_LEVEL=28
    - ANDROID_BUILD_TOOLS_VERSION=28.0.3
    - TRAVIS_SECURE_ENV_VARS=true

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - tools
    - platform-tools
    
    # The SDK version used to compile your project
    - ndroid-$ANDROID_API_LEVEL
    
    # The BuildTools version used by your project
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    
    # Additional components
    - extra-android-support
    - extra-android-m2repository

notifications:
  email: false

# as per http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/
sudo: false

# Caching: https://docs.travis-ci.com/user/languages/android/#Default-Test-Command-for-Gradle
#before_cache:
#  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
#  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

#cache:
#  directories:
#    - $HOME/.gradle/caches/
#    - $HOME/.gradle/wrapper/
#    - $HOME/.android/build-cache

# Command to run
script:
  - ./gradlew clean
  - ./gradlew assembleDebug
